# Generated by Django 3.1.6 on 2022-11-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('post', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
    ]
