# Generated by Django 3.1.6 on 2022-11-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feid', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=1000)),
                ('sid', models.IntegerField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
