# Generated by Django 3.1.6 on 2022-11-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentreg',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('regno', models.IntegerField()),
                ('mobileno', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'studentreg',
                'managed': False,
            },
        ),
    ]
